export enum SocketEvents {
  // state
  STATE_SETUP = 'setup',
  STATE_WAITING = 'waiting',
  STATE_LOBBY = 'lobby',
  STATE_PLAYING = 'playing',
  STATE_STORYTELLING = 'storytelling',
  STATE_ENDED = 'ended',

  // on
  ON_CONFIG_GAME = 'config-game',
  ON_JOIN_GAME = 'join-game',
  ON_REJOIN_GAME = 'rejoin-game',
  ON_START_GAME = 'start-game',
  ON_LEAVE_GAME = 'leave-game',
  ON_CARDS_SELECTED = 'cards-selected',
  ON_FINISH_STORYTELLING = 'finish-storytelling',
  ON_DISCONNECT = 'disconnect',
  ON_RESET_GAME = 'reset-game',
  ON_GET_ROOMS = 'get-rooms',

  // emit
  EMIT_CONFIG_ERROR = 'config-error',
  EMIT_JOIN_ERROR = 'join-error',
  EMIT_JOIN_ACK = 'join-ack',
  EMIT_REJOIN_ERROR = 'rejoin-error',
  EMIT_REJOIN_ACK = 'rejoin-ack',
  EMIT_PLAYER_RECONNECTED = 'player-reconnected',
  EMIT_LEAVE_ERROR = 'leave-error',
  EMIT_START_ERROR = 'start-error',
  EMIT_PLAYER_TURN = 'player-turn',
  EMIT_PLAYER_SELECTED_CARDS = 'player-selected-cards',
  EMIT_PLAYER_DISCONNECTED = 'player-disconnected',
  EMIT_CARDS_SELECTED_ERROR = 'cards-selected-error',
  EMIT_ROOMS_UPDATED = 'rooms-updated',
  EMIT_ROOM_CONFIG = 'room-config',
  EMIT_GAME_STATE = 'game-state',
  EMIT_GAME_ENDED = 'game-ended',
  EMIT_GAME_RESET = 'game-reset',
}
